# .github/workflows/deploy.yml

name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Añadimos la configuración para pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10 # O la versión de pnpm que uses

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          #  Cambiamos la caché a pnpm
          cache: "pnpm"

      # Usamos pnpm para instalar
      - name: Install Dependencies
        run: pnpm install

      # Usamos pnpm para construir
      - name: Build
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
